# Generated by Django 3.1.3 on 2020-11-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoriatabla',
            },
        ),
    ]
